application: krmboya
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /blog/(register|login).*
  login: admin
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest